# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 20:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('article', models.CharField(max_length=300)),
                ('intro', models.CharField(max_length=500)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[(0, 'Open'), (1, 'Skipped'), (2, 'Shared')], default=0, max_length=1)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
