# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170716_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
