# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20170716_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='intro',
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
