# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20170716_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='added',
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
